# Generated by Django 6.0.3 on 2026-03-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='estimated_days',
        ),
    ]
