# Generated by Django 6.0.3 on 2026-03-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('NGN', 'Nigerian Naira'), ('CAD', 'Canadian Dollar'), ('GHS', 'Ghanaian Cedi')], default='GBP', max_length=3),
        ),
    ]
