# Generated by Django 6.0.3 on 2026-03-28 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_add_order_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_reference', models.CharField(max_length=100, unique=True)),
                ('current_status', models.CharField(choices=[('booked', 'Booked'), ('collected', 'Collected'), ('in_transit', 'In Transit'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered')], default='booked', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='checkout.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('collected', 'Collected'), ('in_transit', 'In Transit'), ('customs', 'Customs Clearance'), ('delivered', 'Delivered')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tracking.shipment')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
